(require 'ca-ai)
(require 'ca-clojure)
(require 'ca-devops)
(require 'ca-git)
(require 'ca-project)
(require 'ca-python)
(require 'ca-research)
(require 'ca-sql)
(require 'ca-treesit)
(require 'ca-web)
(require 'ca-shell)
(require 'ca-writing)
(require 'ca-mobile)

(provide 'ca-all)
